export default {
    login: "viettu2k",
    id: 80084954,
    node_id: "MDQ6VXNlcjgwMDg0OTU0",
    avatar_url: "https://avatars.githubusercontent.com/u/80084954?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/viettu2k",
    html_url: "https://github.com/viettu2k",
    followers_url: "https://api.github.com/users/viettu2k/followers",
    following_url: "https://api.github.com/users/viettu2k/following{/other_user}",
    gists_url: "https://api.github.com/users/viettu2k/gists{/gist_id}",
    starred_url: "https://api.github.com/users/viettu2k/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/viettu2k/subscriptions",
    organizations_url: "https://api.github.com/users/viettu2k/orgs",
    repos_url: "https://api.github.com/users/viettu2k/repos",
    events_url: "https://api.github.com/users/viettu2k/events{/privacy}",
    received_events_url: "https://api.github.com/users/viettu2k/received_events",
    type: "User",
    site_admin: false,
    name: "Đoàn Việt Tú",
    company: null,
    blog: "",
    location: null,
    email: null,
    hireable: null,
    bio: null,
    twitter_username: null,
    public_repos: 45,
    public_gists: 0,
    followers: 4,
    following: 4,
    created_at: "2021-03-05T04:12:37Z",
    updated_at: "2021-08-19T12:42:17Z",
};