export default [{
        login: "truongnguyen1582000",
        id: 55800296,
        node_id: "MDQ6VXNlcjU1ODAwMjk2",
        avatar_url: "https://avatars.githubusercontent.com/u/55800296?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/truongnguyen1582000",
        html_url: "https://github.com/truongnguyen1582000",
        followers_url: "https://api.github.com/users/truongnguyen1582000/followers",
        following_url: "https://api.github.com/users/truongnguyen1582000/following{/other_user}",
        gists_url: "https://api.github.com/users/truongnguyen1582000/gists{/gist_id}",
        starred_url: "https://api.github.com/users/truongnguyen1582000/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/truongnguyen1582000/subscriptions",
        organizations_url: "https://api.github.com/users/truongnguyen1582000/orgs",
        repos_url: "https://api.github.com/users/truongnguyen1582000/repos",
        events_url: "https://api.github.com/users/truongnguyen1582000/events{/privacy}",
        received_events_url: "https://api.github.com/users/truongnguyen1582000/received_events",
        type: "User",
        site_admin: false,
    },
    {
        login: "katynguyen96",
        id: 56082798,
        node_id: "MDQ6VXNlcjU2MDgyNzk4",
        avatar_url: "https://avatars.githubusercontent.com/u/56082798?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/katynguyen96",
        html_url: "https://github.com/katynguyen96",
        followers_url: "https://api.github.com/users/katynguyen96/followers",
        following_url: "https://api.github.com/users/katynguyen96/following{/other_user}",
        gists_url: "https://api.github.com/users/katynguyen96/gists{/gist_id}",
        starred_url: "https://api.github.com/users/katynguyen96/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/katynguyen96/subscriptions",
        organizations_url: "https://api.github.com/users/katynguyen96/orgs",
        repos_url: "https://api.github.com/users/katynguyen96/repos",
        events_url: "https://api.github.com/users/katynguyen96/events{/privacy}",
        received_events_url: "https://api.github.com/users/katynguyen96/received_events",
        type: "User",
        site_admin: false,
    },
    {
        login: "LyTrungHai",
        id: 62179426,
        node_id: "MDQ6VXNlcjYyMTc5NDI2",
        avatar_url: "https://avatars.githubusercontent.com/u/62179426?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/LyTrungHai",
        html_url: "https://github.com/LyTrungHai",
        followers_url: "https://api.github.com/users/LyTrungHai/followers",
        following_url: "https://api.github.com/users/LyTrungHai/following{/other_user}",
        gists_url: "https://api.github.com/users/LyTrungHai/gists{/gist_id}",
        starred_url: "https://api.github.com/users/LyTrungHai/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/LyTrungHai/subscriptions",
        organizations_url: "https://api.github.com/users/LyTrungHai/orgs",
        repos_url: "https://api.github.com/users/LyTrungHai/repos",
        events_url: "https://api.github.com/users/LyTrungHai/events{/privacy}",
        received_events_url: "https://api.github.com/users/LyTrungHai/received_events",
        type: "User",
        site_admin: false,
    },
    {
        login: "Son48",
        id: 63116376,
        node_id: "MDQ6VXNlcjYzMTE2Mzc2",
        avatar_url: "https://avatars.githubusercontent.com/u/63116376?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/Son48",
        html_url: "https://github.com/Son48",
        followers_url: "https://api.github.com/users/Son48/followers",
        following_url: "https://api.github.com/users/Son48/following{/other_user}",
        gists_url: "https://api.github.com/users/Son48/gists{/gist_id}",
        starred_url: "https://api.github.com/users/Son48/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/Son48/subscriptions",
        organizations_url: "https://api.github.com/users/Son48/orgs",
        repos_url: "https://api.github.com/users/Son48/repos",
        events_url: "https://api.github.com/users/Son48/events{/privacy}",
        received_events_url: "https://api.github.com/users/Son48/received_events",
        type: "User",
        site_admin: false,
    },
];